// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bluetooth.proto

#include "Bluetooth.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace HU {
PROTOBUF_CONSTEXPR WifiSecurityReponse::WifiSecurityReponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ssid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bssid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.security_mode_)*/0
  , /*decltype(_impl_.access_point_type_)*/0} {}
struct WifiSecurityReponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WifiSecurityReponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WifiSecurityReponseDefaultTypeInternal() {}
  union {
    WifiSecurityReponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WifiSecurityReponseDefaultTypeInternal _WifiSecurityReponse_default_instance_;
PROTOBUF_CONSTEXPR WifiInfoRequest::WifiInfoRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ip_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.port_)*/0u} {}
struct WifiInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WifiInfoRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WifiInfoRequestDefaultTypeInternal() {}
  union {
    WifiInfoRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WifiInfoRequestDefaultTypeInternal _WifiInfoRequest_default_instance_;
PROTOBUF_CONSTEXPR WifiInfoResponse::WifiInfoResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ip_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.port_)*/0u
  , /*decltype(_impl_.status_)*/1} {}
struct WifiInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WifiInfoResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WifiInfoResponseDefaultTypeInternal() {}
  union {
    WifiInfoResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WifiInfoResponseDefaultTypeInternal _WifiInfoResponse_default_instance_;
}  // namespace HU
static ::_pb::Metadata file_level_metadata_Bluetooth_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Bluetooth_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Bluetooth_2eproto = nullptr;

const uint32_t TableStruct_Bluetooth_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _impl_.ssid_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _impl_.bssid_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _impl_.security_mode_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiSecurityReponse, _impl_.access_point_type_),
  0,
  1,
  2,
  3,
  4,
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoRequest, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoRequest, _impl_.ip_address_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoRequest, _impl_.port_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoResponse, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoResponse, _impl_.ip_address_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoResponse, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::HU::WifiInfoResponse, _impl_.status_),
  0,
  1,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, -1, sizeof(::HU::WifiSecurityReponse)},
  { 16, 24, -1, sizeof(::HU::WifiInfoRequest)},
  { 26, 35, -1, sizeof(::HU::WifiInfoResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::HU::_WifiSecurityReponse_default_instance_._instance,
  &::HU::_WifiInfoRequest_default_instance_._instance,
  &::HU::_WifiInfoResponse_default_instance_._instance,
};

const char descriptor_table_protodef_Bluetooth_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017Bluetooth.proto\022\002HU\"\271\003\n\023WifiSecurityRe"
  "ponse\022\014\n\004ssid\030\001 \002(\t\022\013\n\003key\030\002 \002(\t\022\r\n\005bssi"
  "d\030\003 \002(\t\022;\n\rsecurity_mode\030\004 \002(\0162$.HU.Wifi"
  "SecurityReponse.SecurityMode\022B\n\021access_p"
  "oint_type\030\005 \002(\0162\'.HU.WifiSecurityReponse"
  ".AccessPointType\"\312\001\n\014SecurityMode\022\031\n\025UNK"
  "NOWN_SECURITY_MODE\020\000\022\010\n\004OPEN\020\001\022\n\n\006WEP_64"
  "\020\002\022\013\n\007WEP_128\020\003\022\020\n\014WPA_PERSONAL\020\004\022\021\n\rWPA"
  "2_PERSONAL\020\010\022\025\n\021WPA_WPA2_PERSONAL\020\014\022\022\n\016W"
  "PA_ENTERPRISE\020\024\022\023\n\017WPA2_ENTERPRISE\020\030\022\027\n\023"
  "WPA_WPA2_ENTERPRISE\020\034\"*\n\017AccessPointType"
  "\022\n\n\006STATIC\020\000\022\013\n\007DYNAMIC\020\001\"3\n\017WifiInfoReq"
  "uest\022\022\n\nip_address\030\001 \002(\t\022\014\n\004port\030\002 \001(\r\"\330"
  "\004\n\020WifiInfoResponse\022\022\n\nip_address\030\001 \001(\t\022"
  "\014\n\004port\030\002 \001(\r\022+\n\006status\030\003 \002(\0162\033.HU.WifiI"
  "nfoResponse.Status\"\364\003\n\006Status\022\036\n\032STATUS_"
  "UNSOLICITED_MESSAGE\020\001\022\022\n\016STATUS_SUCCESS\020"
  "\000\022)\n\034STATUS_NO_COMPATIBLE_VERSION\020\377\377\377\377\377\377"
  "\377\377\377\001\022-\n STATUS_WIFI_INACCESSIBLE_CHANNEL"
  "\020\376\377\377\377\377\377\377\377\377\001\022.\n!STATUS_WIFI_INCORRECT_CRE"
  "DENTIALS\020\375\377\377\377\377\377\377\377\377\001\022.\n!STATUS_PROJECTION"
  "_ALREADY_STARTED\020\374\377\377\377\377\377\377\377\377\001\022!\n\024STATUS_WI"
  "FI_DISABLED\020\373\377\377\377\377\377\377\377\377\001\022(\n\033STATUS_WIFI_NO"
  "T_YET_STARTED\020\372\377\377\377\377\377\377\377\377\001\022 \n\023STATUS_INVAL"
  "ID_HOST\020\371\377\377\377\377\377\377\377\377\001\022.\n!STATUS_NO_SUPPORTE"
  "D_WIFI_CHANNELS\020\370\377\377\377\377\377\377\377\377\001\0224\n\'STATUS_INS"
  "TRUCT_USER_TO_CHECK_THE_PHONE\020\367\377\377\377\377\377\377\377\377\001"
  "\022\'\n\032STATUS_PHONE_WIFI_DISABLED\020\366\377\377\377\377\377\377\377\377"
  "\001"
  ;
static ::_pbi::once_flag descriptor_table_Bluetooth_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Bluetooth_2eproto = {
    false, false, 1121, descriptor_table_protodef_Bluetooth_2eproto,
    "Bluetooth.proto",
    &descriptor_table_Bluetooth_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_Bluetooth_2eproto::offsets,
    file_level_metadata_Bluetooth_2eproto, file_level_enum_descriptors_Bluetooth_2eproto,
    file_level_service_descriptors_Bluetooth_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Bluetooth_2eproto_getter() {
  return &descriptor_table_Bluetooth_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Bluetooth_2eproto(&descriptor_table_Bluetooth_2eproto);
namespace HU {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WifiSecurityReponse_SecurityMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Bluetooth_2eproto);
  return file_level_enum_descriptors_Bluetooth_2eproto[0];
}
bool WifiSecurityReponse_SecurityMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 8:
    case 12:
    case 20:
    case 24:
    case 28:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::UNKNOWN_SECURITY_MODE;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::OPEN;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WEP_64;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WEP_128;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WPA_PERSONAL;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WPA2_PERSONAL;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WPA_WPA2_PERSONAL;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WPA_ENTERPRISE;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WPA2_ENTERPRISE;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::WPA_WPA2_ENTERPRISE;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::SecurityMode_MIN;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse::SecurityMode_MAX;
constexpr int WifiSecurityReponse::SecurityMode_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WifiSecurityReponse_AccessPointType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Bluetooth_2eproto);
  return file_level_enum_descriptors_Bluetooth_2eproto[1];
}
bool WifiSecurityReponse_AccessPointType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr WifiSecurityReponse_AccessPointType WifiSecurityReponse::STATIC;
constexpr WifiSecurityReponse_AccessPointType WifiSecurityReponse::DYNAMIC;
constexpr WifiSecurityReponse_AccessPointType WifiSecurityReponse::AccessPointType_MIN;
constexpr WifiSecurityReponse_AccessPointType WifiSecurityReponse::AccessPointType_MAX;
constexpr int WifiSecurityReponse::AccessPointType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WifiInfoResponse_Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Bluetooth_2eproto);
  return file_level_enum_descriptors_Bluetooth_2eproto[2];
}
bool WifiInfoResponse_Status_IsValid(int value) {
  switch (value) {
    case -10:
    case -9:
    case -8:
    case -7:
    case -6:
    case -5:
    case -4:
    case -3:
    case -2:
    case -1:
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_UNSOLICITED_MESSAGE;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_SUCCESS;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_NO_COMPATIBLE_VERSION;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_WIFI_INACCESSIBLE_CHANNEL;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_WIFI_INCORRECT_CREDENTIALS;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_PROJECTION_ALREADY_STARTED;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_WIFI_DISABLED;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_WIFI_NOT_YET_STARTED;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_INVALID_HOST;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_NO_SUPPORTED_WIFI_CHANNELS;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE;
constexpr WifiInfoResponse_Status WifiInfoResponse::STATUS_PHONE_WIFI_DISABLED;
constexpr WifiInfoResponse_Status WifiInfoResponse::Status_MIN;
constexpr WifiInfoResponse_Status WifiInfoResponse::Status_MAX;
constexpr int WifiInfoResponse::Status_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class WifiSecurityReponse::_Internal {
 public:
  using HasBits = decltype(std::declval<WifiSecurityReponse>()._impl_._has_bits_);
  static void set_has_ssid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_bssid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_security_mode(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_access_point_type(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000001f) ^ 0x0000001f) != 0;
  }
};

WifiSecurityReponse::WifiSecurityReponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HU.WifiSecurityReponse)
}
WifiSecurityReponse::WifiSecurityReponse(const WifiSecurityReponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WifiSecurityReponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ssid_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.bssid_){}
    , decltype(_impl_.security_mode_){}
    , decltype(_impl_.access_point_type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_ssid()) {
    _this->_impl_.ssid_.Set(from._internal_ssid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_key()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.bssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_bssid()) {
    _this->_impl_.bssid_.Set(from._internal_bssid(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.security_mode_, &from._impl_.security_mode_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.access_point_type_) -
    reinterpret_cast<char*>(&_impl_.security_mode_)) + sizeof(_impl_.access_point_type_));
  // @@protoc_insertion_point(copy_constructor:HU.WifiSecurityReponse)
}

inline void WifiSecurityReponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ssid_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.bssid_){}
    , decltype(_impl_.security_mode_){0}
    , decltype(_impl_.access_point_type_){0}
  };
  _impl_.ssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.bssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WifiSecurityReponse::~WifiSecurityReponse() {
  // @@protoc_insertion_point(destructor:HU.WifiSecurityReponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WifiSecurityReponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ssid_.Destroy();
  _impl_.key_.Destroy();
  _impl_.bssid_.Destroy();
}

void WifiSecurityReponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WifiSecurityReponse::Clear() {
// @@protoc_insertion_point(message_clear_start:HU.WifiSecurityReponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.ssid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.bssid_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    ::memset(&_impl_.security_mode_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.access_point_type_) -
        reinterpret_cast<char*>(&_impl_.security_mode_)) + sizeof(_impl_.access_point_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WifiSecurityReponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string ssid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ssid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HU.WifiSecurityReponse.ssid");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // required string key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HU.WifiSecurityReponse.key");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // required string bssid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_bssid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HU.WifiSecurityReponse.bssid");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // required .HU.WifiSecurityReponse.SecurityMode security_mode = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::HU::WifiSecurityReponse_SecurityMode_IsValid(val))) {
            _internal_set_security_mode(static_cast<::HU::WifiSecurityReponse_SecurityMode>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(4, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // required .HU.WifiSecurityReponse.AccessPointType access_point_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::HU::WifiSecurityReponse_AccessPointType_IsValid(val))) {
            _internal_set_access_point_type(static_cast<::HU::WifiSecurityReponse_AccessPointType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(5, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WifiSecurityReponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HU.WifiSecurityReponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string ssid = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_ssid().data(), static_cast<int>(this->_internal_ssid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HU.WifiSecurityReponse.ssid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ssid(), target);
  }

  // required string key = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HU.WifiSecurityReponse.key");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_key(), target);
  }

  // required string bssid = 3;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_bssid().data(), static_cast<int>(this->_internal_bssid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HU.WifiSecurityReponse.bssid");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_bssid(), target);
  }

  // required .HU.WifiSecurityReponse.SecurityMode security_mode = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_security_mode(), target);
  }

  // required .HU.WifiSecurityReponse.AccessPointType access_point_type = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_access_point_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HU.WifiSecurityReponse)
  return target;
}

size_t WifiSecurityReponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:HU.WifiSecurityReponse)
  size_t total_size = 0;

  if (_internal_has_ssid()) {
    // required string ssid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());
  }

  if (_internal_has_key()) {
    // required string key = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  if (_internal_has_bssid()) {
    // required string bssid = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bssid());
  }

  if (_internal_has_security_mode()) {
    // required .HU.WifiSecurityReponse.SecurityMode security_mode = 4;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_security_mode());
  }

  if (_internal_has_access_point_type()) {
    // required .HU.WifiSecurityReponse.AccessPointType access_point_type = 5;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_access_point_type());
  }

  return total_size;
}
size_t WifiSecurityReponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HU.WifiSecurityReponse)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required string ssid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());

    // required string key = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());

    // required string bssid = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bssid());

    // required .HU.WifiSecurityReponse.SecurityMode security_mode = 4;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_security_mode());

    // required .HU.WifiSecurityReponse.AccessPointType access_point_type = 5;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_access_point_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WifiSecurityReponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WifiSecurityReponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WifiSecurityReponse::GetClassData() const { return &_class_data_; }


void WifiSecurityReponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WifiSecurityReponse*>(&to_msg);
  auto& from = static_cast<const WifiSecurityReponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HU.WifiSecurityReponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_ssid(from._internal_ssid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_key(from._internal_key());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_bssid(from._internal_bssid());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.security_mode_ = from._impl_.security_mode_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.access_point_type_ = from._impl_.access_point_type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WifiSecurityReponse::CopyFrom(const WifiSecurityReponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HU.WifiSecurityReponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WifiSecurityReponse::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void WifiSecurityReponse::InternalSwap(WifiSecurityReponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ssid_, lhs_arena,
      &other->_impl_.ssid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bssid_, lhs_arena,
      &other->_impl_.bssid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WifiSecurityReponse, _impl_.access_point_type_)
      + sizeof(WifiSecurityReponse::_impl_.access_point_type_)
      - PROTOBUF_FIELD_OFFSET(WifiSecurityReponse, _impl_.security_mode_)>(
          reinterpret_cast<char*>(&_impl_.security_mode_),
          reinterpret_cast<char*>(&other->_impl_.security_mode_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WifiSecurityReponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Bluetooth_2eproto_getter, &descriptor_table_Bluetooth_2eproto_once,
      file_level_metadata_Bluetooth_2eproto[0]);
}

// ===================================================================

class WifiInfoRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<WifiInfoRequest>()._impl_._has_bits_);
  static void set_has_ip_address(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_port(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

WifiInfoRequest::WifiInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HU.WifiInfoRequest)
}
WifiInfoRequest::WifiInfoRequest(const WifiInfoRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WifiInfoRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_ip_address()) {
    _this->_impl_.ip_address_.Set(from._internal_ip_address(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.port_ = from._impl_.port_;
  // @@protoc_insertion_point(copy_constructor:HU.WifiInfoRequest)
}

inline void WifiInfoRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){0u}
  };
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WifiInfoRequest::~WifiInfoRequest() {
  // @@protoc_insertion_point(destructor:HU.WifiInfoRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WifiInfoRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_address_.Destroy();
}

void WifiInfoRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WifiInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:HU.WifiInfoRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.ip_address_.ClearNonDefaultToEmpty();
  }
  _impl_.port_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WifiInfoRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string ip_address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ip_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HU.WifiInfoRequest.ip_address");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional uint32 port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_port(&has_bits);
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WifiInfoRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HU.WifiInfoRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string ip_address = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_ip_address().data(), static_cast<int>(this->_internal_ip_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HU.WifiInfoRequest.ip_address");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ip_address(), target);
  }

  // optional uint32 port = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HU.WifiInfoRequest)
  return target;
}

size_t WifiInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HU.WifiInfoRequest)
  size_t total_size = 0;

  // required string ip_address = 1;
  if (_internal_has_ip_address()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip_address());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint32 port = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000002u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WifiInfoRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WifiInfoRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WifiInfoRequest::GetClassData() const { return &_class_data_; }


void WifiInfoRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WifiInfoRequest*>(&to_msg);
  auto& from = static_cast<const WifiInfoRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HU.WifiInfoRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_ip_address(from._internal_ip_address());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.port_ = from._impl_.port_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WifiInfoRequest::CopyFrom(const WifiInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HU.WifiInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WifiInfoRequest::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void WifiInfoRequest::InternalSwap(WifiInfoRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_address_, lhs_arena,
      &other->_impl_.ip_address_, rhs_arena
  );
  swap(_impl_.port_, other->_impl_.port_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WifiInfoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Bluetooth_2eproto_getter, &descriptor_table_Bluetooth_2eproto_once,
      file_level_metadata_Bluetooth_2eproto[1]);
}

// ===================================================================

class WifiInfoResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<WifiInfoResponse>()._impl_._has_bits_);
  static void set_has_ip_address(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_port(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_status(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000004) ^ 0x00000004) != 0;
  }
};

WifiInfoResponse::WifiInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HU.WifiInfoResponse)
}
WifiInfoResponse::WifiInfoResponse(const WifiInfoResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WifiInfoResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.status_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_ip_address()) {
    _this->_impl_.ip_address_.Set(from._internal_ip_address(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.port_, &from._impl_.port_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_) -
    reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.status_));
  // @@protoc_insertion_point(copy_constructor:HU.WifiInfoResponse)
}

inline void WifiInfoResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){0u}
    , decltype(_impl_.status_){1}
  };
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WifiInfoResponse::~WifiInfoResponse() {
  // @@protoc_insertion_point(destructor:HU.WifiInfoResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WifiInfoResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_address_.Destroy();
}

void WifiInfoResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WifiInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:HU.WifiInfoResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.ip_address_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    _impl_.port_ = 0u;
    _impl_.status_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WifiInfoResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string ip_address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ip_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "HU.WifiInfoResponse.ip_address");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional uint32 port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_port(&has_bits);
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required .HU.WifiInfoResponse.Status status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::HU::WifiInfoResponse_Status_IsValid(val))) {
            _internal_set_status(static_cast<::HU::WifiInfoResponse_Status>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WifiInfoResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HU.WifiInfoResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string ip_address = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_ip_address().data(), static_cast<int>(this->_internal_ip_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "HU.WifiInfoResponse.ip_address");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ip_address(), target);
  }

  // optional uint32 port = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_port(), target);
  }

  // required .HU.WifiInfoResponse.Status status = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HU.WifiInfoResponse)
  return target;
}

size_t WifiInfoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HU.WifiInfoResponse)
  size_t total_size = 0;

  // required .HU.WifiInfoResponse.Status status = 3;
  if (_internal_has_status()) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string ip_address = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_ip_address());
    }

    // optional uint32 port = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WifiInfoResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WifiInfoResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WifiInfoResponse::GetClassData() const { return &_class_data_; }


void WifiInfoResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WifiInfoResponse*>(&to_msg);
  auto& from = static_cast<const WifiInfoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HU.WifiInfoResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_ip_address(from._internal_ip_address());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.port_ = from._impl_.port_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.status_ = from._impl_.status_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WifiInfoResponse::CopyFrom(const WifiInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HU.WifiInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WifiInfoResponse::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void WifiInfoResponse::InternalSwap(WifiInfoResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_address_, lhs_arena,
      &other->_impl_.ip_address_, rhs_arena
  );
  swap(_impl_.port_, other->_impl_.port_);
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WifiInfoResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Bluetooth_2eproto_getter, &descriptor_table_Bluetooth_2eproto_once,
      file_level_metadata_Bluetooth_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace HU
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HU::WifiSecurityReponse*
Arena::CreateMaybeMessage< ::HU::WifiSecurityReponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HU::WifiSecurityReponse >(arena);
}
template<> PROTOBUF_NOINLINE ::HU::WifiInfoRequest*
Arena::CreateMaybeMessage< ::HU::WifiInfoRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HU::WifiInfoRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::HU::WifiInfoResponse*
Arena::CreateMaybeMessage< ::HU::WifiInfoResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HU::WifiInfoResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
