// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bluetooth.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Bluetooth_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Bluetooth_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Bluetooth_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Bluetooth_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Bluetooth_2eproto;
namespace HU {
class WifiInfoRequest;
struct WifiInfoRequestDefaultTypeInternal;
extern WifiInfoRequestDefaultTypeInternal _WifiInfoRequest_default_instance_;
class WifiInfoResponse;
struct WifiInfoResponseDefaultTypeInternal;
extern WifiInfoResponseDefaultTypeInternal _WifiInfoResponse_default_instance_;
class WifiSecurityReponse;
struct WifiSecurityReponseDefaultTypeInternal;
extern WifiSecurityReponseDefaultTypeInternal _WifiSecurityReponse_default_instance_;
}  // namespace HU
PROTOBUF_NAMESPACE_OPEN
template<> ::HU::WifiInfoRequest* Arena::CreateMaybeMessage<::HU::WifiInfoRequest>(Arena*);
template<> ::HU::WifiInfoResponse* Arena::CreateMaybeMessage<::HU::WifiInfoResponse>(Arena*);
template<> ::HU::WifiSecurityReponse* Arena::CreateMaybeMessage<::HU::WifiSecurityReponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HU {

enum WifiSecurityReponse_SecurityMode : int {
  WifiSecurityReponse_SecurityMode_UNKNOWN_SECURITY_MODE = 0,
  WifiSecurityReponse_SecurityMode_OPEN = 1,
  WifiSecurityReponse_SecurityMode_WEP_64 = 2,
  WifiSecurityReponse_SecurityMode_WEP_128 = 3,
  WifiSecurityReponse_SecurityMode_WPA_PERSONAL = 4,
  WifiSecurityReponse_SecurityMode_WPA2_PERSONAL = 8,
  WifiSecurityReponse_SecurityMode_WPA_WPA2_PERSONAL = 12,
  WifiSecurityReponse_SecurityMode_WPA_ENTERPRISE = 20,
  WifiSecurityReponse_SecurityMode_WPA2_ENTERPRISE = 24,
  WifiSecurityReponse_SecurityMode_WPA_WPA2_ENTERPRISE = 28
};
bool WifiSecurityReponse_SecurityMode_IsValid(int value);
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse_SecurityMode_SecurityMode_MIN = WifiSecurityReponse_SecurityMode_UNKNOWN_SECURITY_MODE;
constexpr WifiSecurityReponse_SecurityMode WifiSecurityReponse_SecurityMode_SecurityMode_MAX = WifiSecurityReponse_SecurityMode_WPA_WPA2_ENTERPRISE;
constexpr int WifiSecurityReponse_SecurityMode_SecurityMode_ARRAYSIZE = WifiSecurityReponse_SecurityMode_SecurityMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WifiSecurityReponse_SecurityMode_descriptor();
template<typename T>
inline const std::string& WifiSecurityReponse_SecurityMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WifiSecurityReponse_SecurityMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WifiSecurityReponse_SecurityMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WifiSecurityReponse_SecurityMode_descriptor(), enum_t_value);
}
inline bool WifiSecurityReponse_SecurityMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WifiSecurityReponse_SecurityMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WifiSecurityReponse_SecurityMode>(
    WifiSecurityReponse_SecurityMode_descriptor(), name, value);
}
enum WifiSecurityReponse_AccessPointType : int {
  WifiSecurityReponse_AccessPointType_STATIC = 0,
  WifiSecurityReponse_AccessPointType_DYNAMIC = 1
};
bool WifiSecurityReponse_AccessPointType_IsValid(int value);
constexpr WifiSecurityReponse_AccessPointType WifiSecurityReponse_AccessPointType_AccessPointType_MIN = WifiSecurityReponse_AccessPointType_STATIC;
constexpr WifiSecurityReponse_AccessPointType WifiSecurityReponse_AccessPointType_AccessPointType_MAX = WifiSecurityReponse_AccessPointType_DYNAMIC;
constexpr int WifiSecurityReponse_AccessPointType_AccessPointType_ARRAYSIZE = WifiSecurityReponse_AccessPointType_AccessPointType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WifiSecurityReponse_AccessPointType_descriptor();
template<typename T>
inline const std::string& WifiSecurityReponse_AccessPointType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WifiSecurityReponse_AccessPointType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WifiSecurityReponse_AccessPointType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WifiSecurityReponse_AccessPointType_descriptor(), enum_t_value);
}
inline bool WifiSecurityReponse_AccessPointType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WifiSecurityReponse_AccessPointType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WifiSecurityReponse_AccessPointType>(
    WifiSecurityReponse_AccessPointType_descriptor(), name, value);
}
enum WifiInfoResponse_Status : int {
  WifiInfoResponse_Status_STATUS_UNSOLICITED_MESSAGE = 1,
  WifiInfoResponse_Status_STATUS_SUCCESS = 0,
  WifiInfoResponse_Status_STATUS_NO_COMPATIBLE_VERSION = -1,
  WifiInfoResponse_Status_STATUS_WIFI_INACCESSIBLE_CHANNEL = -2,
  WifiInfoResponse_Status_STATUS_WIFI_INCORRECT_CREDENTIALS = -3,
  WifiInfoResponse_Status_STATUS_PROJECTION_ALREADY_STARTED = -4,
  WifiInfoResponse_Status_STATUS_WIFI_DISABLED = -5,
  WifiInfoResponse_Status_STATUS_WIFI_NOT_YET_STARTED = -6,
  WifiInfoResponse_Status_STATUS_INVALID_HOST = -7,
  WifiInfoResponse_Status_STATUS_NO_SUPPORTED_WIFI_CHANNELS = -8,
  WifiInfoResponse_Status_STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE = -9,
  WifiInfoResponse_Status_STATUS_PHONE_WIFI_DISABLED = -10
};
bool WifiInfoResponse_Status_IsValid(int value);
constexpr WifiInfoResponse_Status WifiInfoResponse_Status_Status_MIN = WifiInfoResponse_Status_STATUS_PHONE_WIFI_DISABLED;
constexpr WifiInfoResponse_Status WifiInfoResponse_Status_Status_MAX = WifiInfoResponse_Status_STATUS_UNSOLICITED_MESSAGE;
constexpr int WifiInfoResponse_Status_Status_ARRAYSIZE = WifiInfoResponse_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WifiInfoResponse_Status_descriptor();
template<typename T>
inline const std::string& WifiInfoResponse_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WifiInfoResponse_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WifiInfoResponse_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WifiInfoResponse_Status_descriptor(), enum_t_value);
}
inline bool WifiInfoResponse_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WifiInfoResponse_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WifiInfoResponse_Status>(
    WifiInfoResponse_Status_descriptor(), name, value);
}
// ===================================================================

class WifiSecurityReponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HU.WifiSecurityReponse) */ {
 public:
  inline WifiSecurityReponse() : WifiSecurityReponse(nullptr) {}
  ~WifiSecurityReponse() override;
  explicit PROTOBUF_CONSTEXPR WifiSecurityReponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WifiSecurityReponse(const WifiSecurityReponse& from);
  WifiSecurityReponse(WifiSecurityReponse&& from) noexcept
    : WifiSecurityReponse() {
    *this = ::std::move(from);
  }

  inline WifiSecurityReponse& operator=(const WifiSecurityReponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WifiSecurityReponse& operator=(WifiSecurityReponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WifiSecurityReponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const WifiSecurityReponse* internal_default_instance() {
    return reinterpret_cast<const WifiSecurityReponse*>(
               &_WifiSecurityReponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WifiSecurityReponse& a, WifiSecurityReponse& b) {
    a.Swap(&b);
  }
  inline void Swap(WifiSecurityReponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WifiSecurityReponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WifiSecurityReponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WifiSecurityReponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WifiSecurityReponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WifiSecurityReponse& from) {
    WifiSecurityReponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WifiSecurityReponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HU.WifiSecurityReponse";
  }
  protected:
  explicit WifiSecurityReponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef WifiSecurityReponse_SecurityMode SecurityMode;
  static constexpr SecurityMode UNKNOWN_SECURITY_MODE =
    WifiSecurityReponse_SecurityMode_UNKNOWN_SECURITY_MODE;
  static constexpr SecurityMode OPEN =
    WifiSecurityReponse_SecurityMode_OPEN;
  static constexpr SecurityMode WEP_64 =
    WifiSecurityReponse_SecurityMode_WEP_64;
  static constexpr SecurityMode WEP_128 =
    WifiSecurityReponse_SecurityMode_WEP_128;
  static constexpr SecurityMode WPA_PERSONAL =
    WifiSecurityReponse_SecurityMode_WPA_PERSONAL;
  static constexpr SecurityMode WPA2_PERSONAL =
    WifiSecurityReponse_SecurityMode_WPA2_PERSONAL;
  static constexpr SecurityMode WPA_WPA2_PERSONAL =
    WifiSecurityReponse_SecurityMode_WPA_WPA2_PERSONAL;
  static constexpr SecurityMode WPA_ENTERPRISE =
    WifiSecurityReponse_SecurityMode_WPA_ENTERPRISE;
  static constexpr SecurityMode WPA2_ENTERPRISE =
    WifiSecurityReponse_SecurityMode_WPA2_ENTERPRISE;
  static constexpr SecurityMode WPA_WPA2_ENTERPRISE =
    WifiSecurityReponse_SecurityMode_WPA_WPA2_ENTERPRISE;
  static inline bool SecurityMode_IsValid(int value) {
    return WifiSecurityReponse_SecurityMode_IsValid(value);
  }
  static constexpr SecurityMode SecurityMode_MIN =
    WifiSecurityReponse_SecurityMode_SecurityMode_MIN;
  static constexpr SecurityMode SecurityMode_MAX =
    WifiSecurityReponse_SecurityMode_SecurityMode_MAX;
  static constexpr int SecurityMode_ARRAYSIZE =
    WifiSecurityReponse_SecurityMode_SecurityMode_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  SecurityMode_descriptor() {
    return WifiSecurityReponse_SecurityMode_descriptor();
  }
  template<typename T>
  static inline const std::string& SecurityMode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, SecurityMode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function SecurityMode_Name.");
    return WifiSecurityReponse_SecurityMode_Name(enum_t_value);
  }
  static inline bool SecurityMode_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      SecurityMode* value) {
    return WifiSecurityReponse_SecurityMode_Parse(name, value);
  }

  typedef WifiSecurityReponse_AccessPointType AccessPointType;
  static constexpr AccessPointType STATIC =
    WifiSecurityReponse_AccessPointType_STATIC;
  static constexpr AccessPointType DYNAMIC =
    WifiSecurityReponse_AccessPointType_DYNAMIC;
  static inline bool AccessPointType_IsValid(int value) {
    return WifiSecurityReponse_AccessPointType_IsValid(value);
  }
  static constexpr AccessPointType AccessPointType_MIN =
    WifiSecurityReponse_AccessPointType_AccessPointType_MIN;
  static constexpr AccessPointType AccessPointType_MAX =
    WifiSecurityReponse_AccessPointType_AccessPointType_MAX;
  static constexpr int AccessPointType_ARRAYSIZE =
    WifiSecurityReponse_AccessPointType_AccessPointType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  AccessPointType_descriptor() {
    return WifiSecurityReponse_AccessPointType_descriptor();
  }
  template<typename T>
  static inline const std::string& AccessPointType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, AccessPointType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function AccessPointType_Name.");
    return WifiSecurityReponse_AccessPointType_Name(enum_t_value);
  }
  static inline bool AccessPointType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      AccessPointType* value) {
    return WifiSecurityReponse_AccessPointType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSsidFieldNumber = 1,
    kKeyFieldNumber = 2,
    kBssidFieldNumber = 3,
    kSecurityModeFieldNumber = 4,
    kAccessPointTypeFieldNumber = 5,
  };
  // required string ssid = 1;
  bool has_ssid() const;
  private:
  bool _internal_has_ssid() const;
  public:
  void clear_ssid();
  const std::string& ssid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ssid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ssid();
  PROTOBUF_NODISCARD std::string* release_ssid();
  void set_allocated_ssid(std::string* ssid);
  private:
  const std::string& _internal_ssid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ssid(const std::string& value);
  std::string* _internal_mutable_ssid();
  public:

  // required string key = 2;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // required string bssid = 3;
  bool has_bssid() const;
  private:
  bool _internal_has_bssid() const;
  public:
  void clear_bssid();
  const std::string& bssid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bssid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bssid();
  PROTOBUF_NODISCARD std::string* release_bssid();
  void set_allocated_bssid(std::string* bssid);
  private:
  const std::string& _internal_bssid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bssid(const std::string& value);
  std::string* _internal_mutable_bssid();
  public:

  // required .HU.WifiSecurityReponse.SecurityMode security_mode = 4;
  bool has_security_mode() const;
  private:
  bool _internal_has_security_mode() const;
  public:
  void clear_security_mode();
  ::HU::WifiSecurityReponse_SecurityMode security_mode() const;
  void set_security_mode(::HU::WifiSecurityReponse_SecurityMode value);
  private:
  ::HU::WifiSecurityReponse_SecurityMode _internal_security_mode() const;
  void _internal_set_security_mode(::HU::WifiSecurityReponse_SecurityMode value);
  public:

  // required .HU.WifiSecurityReponse.AccessPointType access_point_type = 5;
  bool has_access_point_type() const;
  private:
  bool _internal_has_access_point_type() const;
  public:
  void clear_access_point_type();
  ::HU::WifiSecurityReponse_AccessPointType access_point_type() const;
  void set_access_point_type(::HU::WifiSecurityReponse_AccessPointType value);
  private:
  ::HU::WifiSecurityReponse_AccessPointType _internal_access_point_type() const;
  void _internal_set_access_point_type(::HU::WifiSecurityReponse_AccessPointType value);
  public:

  // @@protoc_insertion_point(class_scope:HU.WifiSecurityReponse)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ssid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bssid_;
    int security_mode_;
    int access_point_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Bluetooth_2eproto;
};
// -------------------------------------------------------------------

class WifiInfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HU.WifiInfoRequest) */ {
 public:
  inline WifiInfoRequest() : WifiInfoRequest(nullptr) {}
  ~WifiInfoRequest() override;
  explicit PROTOBUF_CONSTEXPR WifiInfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WifiInfoRequest(const WifiInfoRequest& from);
  WifiInfoRequest(WifiInfoRequest&& from) noexcept
    : WifiInfoRequest() {
    *this = ::std::move(from);
  }

  inline WifiInfoRequest& operator=(const WifiInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WifiInfoRequest& operator=(WifiInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WifiInfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const WifiInfoRequest* internal_default_instance() {
    return reinterpret_cast<const WifiInfoRequest*>(
               &_WifiInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(WifiInfoRequest& a, WifiInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(WifiInfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WifiInfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WifiInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WifiInfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WifiInfoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WifiInfoRequest& from) {
    WifiInfoRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WifiInfoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HU.WifiInfoRequest";
  }
  protected:
  explicit WifiInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpAddressFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // required string ip_address = 1;
  bool has_ip_address() const;
  private:
  bool _internal_has_ip_address() const;
  public:
  void clear_ip_address();
  const std::string& ip_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip_address();
  PROTOBUF_NODISCARD std::string* release_ip_address();
  void set_allocated_ip_address(std::string* ip_address);
  private:
  const std::string& _internal_ip_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const std::string& value);
  std::string* _internal_mutable_ip_address();
  public:

  // optional uint32 port = 2;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HU.WifiInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_address_;
    uint32_t port_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Bluetooth_2eproto;
};
// -------------------------------------------------------------------

class WifiInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HU.WifiInfoResponse) */ {
 public:
  inline WifiInfoResponse() : WifiInfoResponse(nullptr) {}
  ~WifiInfoResponse() override;
  explicit PROTOBUF_CONSTEXPR WifiInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WifiInfoResponse(const WifiInfoResponse& from);
  WifiInfoResponse(WifiInfoResponse&& from) noexcept
    : WifiInfoResponse() {
    *this = ::std::move(from);
  }

  inline WifiInfoResponse& operator=(const WifiInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WifiInfoResponse& operator=(WifiInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WifiInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const WifiInfoResponse* internal_default_instance() {
    return reinterpret_cast<const WifiInfoResponse*>(
               &_WifiInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(WifiInfoResponse& a, WifiInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(WifiInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WifiInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WifiInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WifiInfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WifiInfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WifiInfoResponse& from) {
    WifiInfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WifiInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HU.WifiInfoResponse";
  }
  protected:
  explicit WifiInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef WifiInfoResponse_Status Status;
  static constexpr Status STATUS_UNSOLICITED_MESSAGE =
    WifiInfoResponse_Status_STATUS_UNSOLICITED_MESSAGE;
  static constexpr Status STATUS_SUCCESS =
    WifiInfoResponse_Status_STATUS_SUCCESS;
  static constexpr Status STATUS_NO_COMPATIBLE_VERSION =
    WifiInfoResponse_Status_STATUS_NO_COMPATIBLE_VERSION;
  static constexpr Status STATUS_WIFI_INACCESSIBLE_CHANNEL =
    WifiInfoResponse_Status_STATUS_WIFI_INACCESSIBLE_CHANNEL;
  static constexpr Status STATUS_WIFI_INCORRECT_CREDENTIALS =
    WifiInfoResponse_Status_STATUS_WIFI_INCORRECT_CREDENTIALS;
  static constexpr Status STATUS_PROJECTION_ALREADY_STARTED =
    WifiInfoResponse_Status_STATUS_PROJECTION_ALREADY_STARTED;
  static constexpr Status STATUS_WIFI_DISABLED =
    WifiInfoResponse_Status_STATUS_WIFI_DISABLED;
  static constexpr Status STATUS_WIFI_NOT_YET_STARTED =
    WifiInfoResponse_Status_STATUS_WIFI_NOT_YET_STARTED;
  static constexpr Status STATUS_INVALID_HOST =
    WifiInfoResponse_Status_STATUS_INVALID_HOST;
  static constexpr Status STATUS_NO_SUPPORTED_WIFI_CHANNELS =
    WifiInfoResponse_Status_STATUS_NO_SUPPORTED_WIFI_CHANNELS;
  static constexpr Status STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE =
    WifiInfoResponse_Status_STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE;
  static constexpr Status STATUS_PHONE_WIFI_DISABLED =
    WifiInfoResponse_Status_STATUS_PHONE_WIFI_DISABLED;
  static inline bool Status_IsValid(int value) {
    return WifiInfoResponse_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    WifiInfoResponse_Status_Status_MIN;
  static constexpr Status Status_MAX =
    WifiInfoResponse_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    WifiInfoResponse_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return WifiInfoResponse_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return WifiInfoResponse_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return WifiInfoResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kIpAddressFieldNumber = 1,
    kPortFieldNumber = 2,
    kStatusFieldNumber = 3,
  };
  // optional string ip_address = 1;
  bool has_ip_address() const;
  private:
  bool _internal_has_ip_address() const;
  public:
  void clear_ip_address();
  const std::string& ip_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip_address();
  PROTOBUF_NODISCARD std::string* release_ip_address();
  void set_allocated_ip_address(std::string* ip_address);
  private:
  const std::string& _internal_ip_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const std::string& value);
  std::string* _internal_mutable_ip_address();
  public:

  // optional uint32 port = 2;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // required .HU.WifiInfoResponse.Status status = 3;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::HU::WifiInfoResponse_Status status() const;
  void set_status(::HU::WifiInfoResponse_Status value);
  private:
  ::HU::WifiInfoResponse_Status _internal_status() const;
  void _internal_set_status(::HU::WifiInfoResponse_Status value);
  public:

  // @@protoc_insertion_point(class_scope:HU.WifiInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_address_;
    uint32_t port_;
    int status_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Bluetooth_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WifiSecurityReponse

// required string ssid = 1;
inline bool WifiSecurityReponse::_internal_has_ssid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool WifiSecurityReponse::has_ssid() const {
  return _internal_has_ssid();
}
inline void WifiSecurityReponse::clear_ssid() {
  _impl_.ssid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& WifiSecurityReponse::ssid() const {
  // @@protoc_insertion_point(field_get:HU.WifiSecurityReponse.ssid)
  return _internal_ssid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiSecurityReponse::set_ssid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.ssid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HU.WifiSecurityReponse.ssid)
}
inline std::string* WifiSecurityReponse::mutable_ssid() {
  std::string* _s = _internal_mutable_ssid();
  // @@protoc_insertion_point(field_mutable:HU.WifiSecurityReponse.ssid)
  return _s;
}
inline const std::string& WifiSecurityReponse::_internal_ssid() const {
  return _impl_.ssid_.Get();
}
inline void WifiSecurityReponse::_internal_set_ssid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ssid_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiSecurityReponse::_internal_mutable_ssid() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ssid_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiSecurityReponse::release_ssid() {
  // @@protoc_insertion_point(field_release:HU.WifiSecurityReponse.ssid)
  if (!_internal_has_ssid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.ssid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ssid_.IsDefault()) {
    _impl_.ssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiSecurityReponse::set_allocated_ssid(std::string* ssid) {
  if (ssid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ssid_.SetAllocated(ssid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ssid_.IsDefault()) {
    _impl_.ssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HU.WifiSecurityReponse.ssid)
}

// required string key = 2;
inline bool WifiSecurityReponse::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool WifiSecurityReponse::has_key() const {
  return _internal_has_key();
}
inline void WifiSecurityReponse::clear_key() {
  _impl_.key_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& WifiSecurityReponse::key() const {
  // @@protoc_insertion_point(field_get:HU.WifiSecurityReponse.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiSecurityReponse::set_key(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HU.WifiSecurityReponse.key)
}
inline std::string* WifiSecurityReponse::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:HU.WifiSecurityReponse.key)
  return _s;
}
inline const std::string& WifiSecurityReponse::_internal_key() const {
  return _impl_.key_.Get();
}
inline void WifiSecurityReponse::_internal_set_key(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiSecurityReponse::_internal_mutable_key() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiSecurityReponse::release_key() {
  // @@protoc_insertion_point(field_release:HU.WifiSecurityReponse.key)
  if (!_internal_has_key()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.key_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiSecurityReponse::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HU.WifiSecurityReponse.key)
}

// required string bssid = 3;
inline bool WifiSecurityReponse::_internal_has_bssid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool WifiSecurityReponse::has_bssid() const {
  return _internal_has_bssid();
}
inline void WifiSecurityReponse::clear_bssid() {
  _impl_.bssid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& WifiSecurityReponse::bssid() const {
  // @@protoc_insertion_point(field_get:HU.WifiSecurityReponse.bssid)
  return _internal_bssid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiSecurityReponse::set_bssid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.bssid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HU.WifiSecurityReponse.bssid)
}
inline std::string* WifiSecurityReponse::mutable_bssid() {
  std::string* _s = _internal_mutable_bssid();
  // @@protoc_insertion_point(field_mutable:HU.WifiSecurityReponse.bssid)
  return _s;
}
inline const std::string& WifiSecurityReponse::_internal_bssid() const {
  return _impl_.bssid_.Get();
}
inline void WifiSecurityReponse::_internal_set_bssid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.bssid_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiSecurityReponse::_internal_mutable_bssid() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.bssid_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiSecurityReponse::release_bssid() {
  // @@protoc_insertion_point(field_release:HU.WifiSecurityReponse.bssid)
  if (!_internal_has_bssid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.bssid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bssid_.IsDefault()) {
    _impl_.bssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiSecurityReponse::set_allocated_bssid(std::string* bssid) {
  if (bssid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.bssid_.SetAllocated(bssid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bssid_.IsDefault()) {
    _impl_.bssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HU.WifiSecurityReponse.bssid)
}

// required .HU.WifiSecurityReponse.SecurityMode security_mode = 4;
inline bool WifiSecurityReponse::_internal_has_security_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool WifiSecurityReponse::has_security_mode() const {
  return _internal_has_security_mode();
}
inline void WifiSecurityReponse::clear_security_mode() {
  _impl_.security_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::HU::WifiSecurityReponse_SecurityMode WifiSecurityReponse::_internal_security_mode() const {
  return static_cast< ::HU::WifiSecurityReponse_SecurityMode >(_impl_.security_mode_);
}
inline ::HU::WifiSecurityReponse_SecurityMode WifiSecurityReponse::security_mode() const {
  // @@protoc_insertion_point(field_get:HU.WifiSecurityReponse.security_mode)
  return _internal_security_mode();
}
inline void WifiSecurityReponse::_internal_set_security_mode(::HU::WifiSecurityReponse_SecurityMode value) {
  assert(::HU::WifiSecurityReponse_SecurityMode_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.security_mode_ = value;
}
inline void WifiSecurityReponse::set_security_mode(::HU::WifiSecurityReponse_SecurityMode value) {
  _internal_set_security_mode(value);
  // @@protoc_insertion_point(field_set:HU.WifiSecurityReponse.security_mode)
}

// required .HU.WifiSecurityReponse.AccessPointType access_point_type = 5;
inline bool WifiSecurityReponse::_internal_has_access_point_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool WifiSecurityReponse::has_access_point_type() const {
  return _internal_has_access_point_type();
}
inline void WifiSecurityReponse::clear_access_point_type() {
  _impl_.access_point_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::HU::WifiSecurityReponse_AccessPointType WifiSecurityReponse::_internal_access_point_type() const {
  return static_cast< ::HU::WifiSecurityReponse_AccessPointType >(_impl_.access_point_type_);
}
inline ::HU::WifiSecurityReponse_AccessPointType WifiSecurityReponse::access_point_type() const {
  // @@protoc_insertion_point(field_get:HU.WifiSecurityReponse.access_point_type)
  return _internal_access_point_type();
}
inline void WifiSecurityReponse::_internal_set_access_point_type(::HU::WifiSecurityReponse_AccessPointType value) {
  assert(::HU::WifiSecurityReponse_AccessPointType_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.access_point_type_ = value;
}
inline void WifiSecurityReponse::set_access_point_type(::HU::WifiSecurityReponse_AccessPointType value) {
  _internal_set_access_point_type(value);
  // @@protoc_insertion_point(field_set:HU.WifiSecurityReponse.access_point_type)
}

// -------------------------------------------------------------------

// WifiInfoRequest

// required string ip_address = 1;
inline bool WifiInfoRequest::_internal_has_ip_address() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool WifiInfoRequest::has_ip_address() const {
  return _internal_has_ip_address();
}
inline void WifiInfoRequest::clear_ip_address() {
  _impl_.ip_address_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& WifiInfoRequest::ip_address() const {
  // @@protoc_insertion_point(field_get:HU.WifiInfoRequest.ip_address)
  return _internal_ip_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiInfoRequest::set_ip_address(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.ip_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HU.WifiInfoRequest.ip_address)
}
inline std::string* WifiInfoRequest::mutable_ip_address() {
  std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:HU.WifiInfoRequest.ip_address)
  return _s;
}
inline const std::string& WifiInfoRequest::_internal_ip_address() const {
  return _impl_.ip_address_.Get();
}
inline void WifiInfoRequest::_internal_set_ip_address(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ip_address_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiInfoRequest::_internal_mutable_ip_address() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ip_address_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiInfoRequest::release_ip_address() {
  // @@protoc_insertion_point(field_release:HU.WifiInfoRequest.ip_address)
  if (!_internal_has_ip_address()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.ip_address_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiInfoRequest::set_allocated_ip_address(std::string* ip_address) {
  if (ip_address != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ip_address_.SetAllocated(ip_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HU.WifiInfoRequest.ip_address)
}

// optional uint32 port = 2;
inline bool WifiInfoRequest::_internal_has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool WifiInfoRequest::has_port() const {
  return _internal_has_port();
}
inline void WifiInfoRequest::clear_port() {
  _impl_.port_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t WifiInfoRequest::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t WifiInfoRequest::port() const {
  // @@protoc_insertion_point(field_get:HU.WifiInfoRequest.port)
  return _internal_port();
}
inline void WifiInfoRequest::_internal_set_port(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_ = value;
}
inline void WifiInfoRequest::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:HU.WifiInfoRequest.port)
}

// -------------------------------------------------------------------

// WifiInfoResponse

// optional string ip_address = 1;
inline bool WifiInfoResponse::_internal_has_ip_address() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_ip_address() const {
  return _internal_has_ip_address();
}
inline void WifiInfoResponse::clear_ip_address() {
  _impl_.ip_address_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& WifiInfoResponse::ip_address() const {
  // @@protoc_insertion_point(field_get:HU.WifiInfoResponse.ip_address)
  return _internal_ip_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiInfoResponse::set_ip_address(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.ip_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HU.WifiInfoResponse.ip_address)
}
inline std::string* WifiInfoResponse::mutable_ip_address() {
  std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:HU.WifiInfoResponse.ip_address)
  return _s;
}
inline const std::string& WifiInfoResponse::_internal_ip_address() const {
  return _impl_.ip_address_.Get();
}
inline void WifiInfoResponse::_internal_set_ip_address(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ip_address_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::_internal_mutable_ip_address() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ip_address_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::release_ip_address() {
  // @@protoc_insertion_point(field_release:HU.WifiInfoResponse.ip_address)
  if (!_internal_has_ip_address()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.ip_address_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiInfoResponse::set_allocated_ip_address(std::string* ip_address) {
  if (ip_address != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ip_address_.SetAllocated(ip_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HU.WifiInfoResponse.ip_address)
}

// optional uint32 port = 2;
inline bool WifiInfoResponse::_internal_has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_port() const {
  return _internal_has_port();
}
inline void WifiInfoResponse::clear_port() {
  _impl_.port_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t WifiInfoResponse::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t WifiInfoResponse::port() const {
  // @@protoc_insertion_point(field_get:HU.WifiInfoResponse.port)
  return _internal_port();
}
inline void WifiInfoResponse::_internal_set_port(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_ = value;
}
inline void WifiInfoResponse::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:HU.WifiInfoResponse.port)
}

// required .HU.WifiInfoResponse.Status status = 3;
inline bool WifiInfoResponse::_internal_has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_status() const {
  return _internal_has_status();
}
inline void WifiInfoResponse::clear_status() {
  _impl_.status_ = 1;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::HU::WifiInfoResponse_Status WifiInfoResponse::_internal_status() const {
  return static_cast< ::HU::WifiInfoResponse_Status >(_impl_.status_);
}
inline ::HU::WifiInfoResponse_Status WifiInfoResponse::status() const {
  // @@protoc_insertion_point(field_get:HU.WifiInfoResponse.status)
  return _internal_status();
}
inline void WifiInfoResponse::_internal_set_status(::HU::WifiInfoResponse_Status value) {
  assert(::HU::WifiInfoResponse_Status_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.status_ = value;
}
inline void WifiInfoResponse::set_status(::HU::WifiInfoResponse_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:HU.WifiInfoResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace HU

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::HU::WifiSecurityReponse_SecurityMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::HU::WifiSecurityReponse_SecurityMode>() {
  return ::HU::WifiSecurityReponse_SecurityMode_descriptor();
}
template <> struct is_proto_enum< ::HU::WifiSecurityReponse_AccessPointType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::HU::WifiSecurityReponse_AccessPointType>() {
  return ::HU::WifiSecurityReponse_AccessPointType_descriptor();
}
template <> struct is_proto_enum< ::HU::WifiInfoResponse_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::HU::WifiInfoResponse_Status>() {
  return ::HU::WifiInfoResponse_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Bluetooth_2eproto
